### PR TITLE
Adding support to the use of InputStream in the constructor.

### PR DESCRIPTION
**Pull request by jalbertcruz**
It's very usefull to have the posibility to use InputStream instead of string path to the models:

InputStream POStaggerURLAsStream = classloader.getResourceAsStream("/enposmaxent.bin");
InputStream SentDetecURLAsStream = classloader.getResourceAsStream("/ensent.bin");
RakeAlgorithm rakeAlg = new RakeAlgorithm(params, POStaggerURLAsStream, SentDetecURLAsStream);

### CODE REVIEW

**Comment by crew102** [comment]
thanks for the contribution @jalbertcruz

**Comment by jalbertcruz** [comment]
Your welcome, 
can you deploy a new version to maven repos?

**Comment by crew102** [comment]
https://repo.maven.apache.org/maven2/io/github/crew102/rapidrake/0.1.3/

**Comment by jalbertcruz** [comment]
Thanks!

**Pull request merged**
